// export const SAVE_STUDENTS = 'SAVE_STUDENTS';
// export const SAVE_COURSE = 'SAVE_COURSE';

export const COURSE_SAVE_START = 'COURSE_SAVE_START';
export const COURSE_SAVE_SUCCESS = 'COURSE_SAVE_SUCCESS';
export const COURSE_SAVE_FAILURE = 'COURSE_SAVE_FAILURE';

export const COURSE_LIST_START = 'COURSE_LIST_START';
export const COURSE_LIST_SUCCESS = 'COURSE_LIST_SUCCESS';
export const COURSE_LIST_FAILURE = 'COURSE_LIST_FAILURE';


export const STUDENT_SAVE_START = 'STUDENT_SAVE_START';
export const STUDENT_SAVE_SUCCESS = 'STUDENT_SAVE_SUCCESS';
export const STUDENT_SAVE_FAILURE = 'STUDENT_SAVE_FAILURE';

export const STUDENT_LIST_START = 'STUDENT_LIST_START';
export const STUDENT_LIST_SUCCESS = 'STUDENT_LIST_SUCCESS';
export const STUDENT_LIST_FAILURE = 'STUDENT_LIST_FAILURE';

export const AUTH_SAVE_START = 'AUTH_SAVE_START';
export const AUTH_SAVE_SUCCESS = 'AUTH_SAVE_SUCCESS';
export const AUTH_SAVE_FAILURE = 'AUTH_SAVE_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';